export const ENDPOINTS = {
  auth: {
    login: "/api/auth/login",
    adminLogin: "/api/admin/auth/login",
    forgotPassword: "/api/auth/forgot-password",
    resetPassword: "/api/auth/reset-password",
    register: "/api/auth/register",
  },
  agentProfile: {
    get: "/api/agent-profile",
    update: "/api/agent-profile/update",
    password: "/api/agent-profile/password",
    photo: "/api/agent-profile/photo",
    fcmToken: "/api/agent-profile/fcm-token",
    inviteLink: "/api/agent-profile/invite-link",
  },
  settings: {
    get: "/api/settings",
    shipping: "/api/settings/shipping",
    discountRules: "/api/settings/discount-rules",
    fees: "/api/settings/fees",
    status: "/api/settings/status",
  },
  notifications: {
    list: "/api/notifications",
    readAll: "/api/notifications/read-all",
    clearAll: "/api/notifications/clear-all",
    byId: (id) => `/api/notifications/${id}`,
    read: (id) => `/api/notifications/${id}/read`,
  },
  dashboard: {
    cardData: "/api/dashboard/card-data",
    orderData: "/api/dashboard/order-data",
    revenueData: "/api/dashboard/revenue-data",
    batchData: "/api/dashboard/batch-data",
  },
  orders: {
    list: "/api/orders",
    export: "/api/orders/export",
    scan: "/api/orders/scan",
    byId: (id) => `/api/orders/${id}`,
    edit: (id) => `/api/orders/${id}/edit`,
    status: (id) => `/api/orders/${id}/status`,
  },
  customers: {
    list: "/api/customers",
    byId: (id) => `/api/customers/${id}`,
  },
  batches: {
    list: "/api/batches",
    approvedOrders: "/api/batches/approved-orders",
    activityLogs: "/api/batches/logs/activity",
    merge: "/api/batches/merge",
    byId: (id) => `/api/batches/${id}`,
    lock: (id) => `/api/batches/${id}/lock`,
    unlock: (id) => `/api/batches/${id}/unlock`,
    moveOrders: (id) => `/api/batches/${id}/move-orders`,
    removeOrders: (id) => `/api/batches/${id}/remove-orders`,
  },
  chat: {
    conversations: "/api/chat/conversations",
    messages: (id) => `/api/chat/conversations/${id}/messages`,
    upload: "/api/chat/upload",
  },
  marketplace: {
    list: "/api/products",
    create: "/api/products",
    byId: (id) => `/api/products/${id}`,
  },
  admin: {
    dashboard: "/api/admin/dashboard",
    activityLogs: "/api/admin/activity-logs",
    getAllAgents: "/api/admin/agents",
    agentById: (id) => `/api/admin/agents/${id}`,
    updateAgentStatus: (id) => `/api/admin/agents/${id}/status`,
  },
};
